from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from .models import KaggleTrainingRequest, KaggleTrainingResponse, TrainingIngestResponse, WorldModelCandidate, utc_now


TEMPLATE_NOTEBOOK = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# JIMS-AI Encoder Fine-Tuning\\n",
                "This notebook is generated by the JIMS-AI Kaggle orchestrator. It consumes SPPE pairs, world-model candidates, and signatures from the unified training pipeline.\\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import json, os, pathlib\\n",
                "from datetime import datetime\\n",
                "payload = json.load(open('/kaggle/working/training_payload.json'))\\n",
                "out = pathlib.Path('/kaggle/working/jimsai_encoder_artifacts')\\n",
                "out.mkdir(exist_ok=True)\\n",
                "print('task', payload['task_type'], 'pairs', len(payload.get('sppe_pairs', [])))\\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Lightweight baseline that always emits an artifact.\\n",
                "# Replace or extend this cell with SentenceTransformer/Nomic fine-tuning when Kaggle GPU is available.\\n",
                "pairs = payload.get('sppe_pairs', [])\\n",
                "world = payload.get('world_model_candidates', [])\\n",
                "vocab = {}\\n",
                "for pair in pairs:\\n",
                "    text = pair.get('original_text', '')\\n",
                "    for token in text.lower().replace('.', ' ').replace(',', ' ').split():\\n",
                "        if len(token) >= 4:\\n",
                "            vocab[token] = vocab.get(token, 0) + 1\\n",
                "manifest = {\\n",
                "    'created_at': datetime.utcnow().isoformat() + 'Z',\\n",
                "    'task_type': payload['task_type'],\\n",
                "    'sppe_pairs': len(pairs),\\n",
                "    'world_model_candidates': len(world),\\n",
                "    'artifact_kind': 'encoder_training_manifest',\\n",
                "    'next_step': 'attach Nomic/SigLIP/HuBERT fine-tuning cells for heavier runs',\\n",
                "}\\n",
                "json.dump(manifest, open(out / 'manifest.json', 'w'), indent=2)\\n",
                "json.dump(dict(sorted(vocab.items(), key=lambda item: (-item[1], item[0]))[:5000]), open(out / 'token_weights.json', 'w'), indent=2)\\n",
                "print(json.dumps(manifest, indent=2))\\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Optional GPU fine-tune hook. Kept explicit so transformers remain training tools, not runtime brains.\\n",
                "if os.getenv('JIMS_RUN_SENTENCE_TRANSFORMER_FINETUNE') == '1' and pairs:\\n",
                "    from sentence_transformers import SentenceTransformer, InputExample, losses\\n",
                "    from torch.utils.data import DataLoader\\n",
                "    model_name = os.getenv('JIMS_ENCODER_BASE_MODEL', 'nomic-ai/nomic-embed-text-v1.5')\\n",
                "    model = SentenceTransformer(model_name, trust_remote_code=True)\\n",
                "    examples = [InputExample(texts=[p['original_text'], json.dumps(p['semantic_intention_graph'])]) for p in pairs]\\n",
                "    loader = DataLoader(examples, shuffle=True, batch_size=8)\\n",
                "    model.fit(train_objectives=[(loader, losses.MultipleNegativesRankingLoss(model))], epochs=1, warmup_steps=10)\\n",
                "    model.save(str(out / 'sentence_transformer'))\\n",
                "    print('saved sentence_transformer artifact')\\n",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}


class KaggleGPUOrchestrator:
    def __init__(self, workspace_root: str | Path = ".kaggle_runs") -> None:
        self.workspace_root = Path(workspace_root)
        self.workspace_root.mkdir(parents=True, exist_ok=True)

    @property
    def configured(self) -> bool:
        return (
            self._kagglehub_available()
            and bool(os.getenv("KAGGLE_API_TOKEN", "").strip())
            and bool(self._dataset_owner())
        )

    def submit_training_run(
        self,
        request: KaggleTrainingRequest,
        training_history: list[TrainingIngestResponse],
        world_model_candidates: list[WorldModelCandidate],
    ) -> KaggleTrainingResponse:
        run_id = f"kaggle_{utc_now().strftime('%Y%m%d_%H%M%S')}_{request.task_type}"
        run_dir = self.workspace_root / run_id
        run_dir.mkdir(parents=True, exist_ok=True)
        payload = self._training_payload(request, training_history, world_model_candidates)
        (run_dir / "training_payload.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
        (run_dir / "dataset-metadata.json").write_text(json.dumps(self._dataset_metadata(request), indent=2), encoding="utf-8")
        (run_dir / "jimsai_encoder_finetune.ipynb").write_text(json.dumps(TEMPLATE_NOTEBOOK, indent=2), encoding="utf-8")

        if not self._kagglehub_available():
            return KaggleTrainingResponse(
                run_id=run_id,
                status="prepared",
                task_type=request.task_type,
                local_path=str(run_dir),
                detail="kagglehub is not installed; training payload package prepared only.",
            )
        if not os.getenv("KAGGLE_API_TOKEN", "").strip():
            return KaggleTrainingResponse(
                run_id=run_id,
                status="prepared",
                task_type=request.task_type,
                local_path=str(run_dir),
                detail="KAGGLE_API_TOKEN is not configured; training payload package prepared only.",
            )
        if not self._dataset_owner():
            return KaggleTrainingResponse(
                run_id=run_id,
                status="prepared",
                task_type=request.task_type,
                local_path=str(run_dir),
                detail="KAGGLE_DATASET_OWNER or KAGGLE_USERNAME is required to upload the private training dataset.",
            )

        dataset_handle = self._dataset_handle(request)
        try:
            import kagglehub

            kagglehub.dataset_upload(
                dataset_handle,
                str(run_dir),
                version_notes=f"{request.task_type}: {request.notes or 'JIMS-AI training payload'}",
                ignore_patterns=["*.tmp", ".cache/"],
            )
        except Exception as exc:
            return KaggleTrainingResponse(
                run_id=run_id,
                status="failed",
                task_type=request.task_type,
                kernel_ref=dataset_handle,
                local_path=str(run_dir),
                detail=str(exc)[-800:],
            )
        return KaggleTrainingResponse(
            run_id=run_id,
            status="submitted",
            task_type=request.task_type,
            kernel_ref=dataset_handle,
            local_path=str(run_dir),
            detail=(
                "KaggleHub uploaded a private training dataset. Attach this dataset to a Kaggle GPU notebook "
                "or use an existing notebook that reads training_payload.json and writes artifacts."
            ),
        )

    def sync_outputs(self, run: KaggleTrainingResponse, output_root: str | Path = ".kaggle_artifacts") -> KaggleTrainingResponse:
        if not run.kernel_ref:
            return run.model_copy(update={"detail": "No Kaggle dataset or notebook output reference is available for this run."})
        if not self._kagglehub_available() or not os.getenv("KAGGLE_API_TOKEN", "").strip():
            return run.model_copy(update={"detail": "kagglehub or KAGGLE_API_TOKEN is unavailable; cannot sync outputs."})
        output_dir = Path(output_root) / run.run_id
        output_dir.mkdir(parents=True, exist_ok=True)
        try:
            import kagglehub

            downloaded = kagglehub.notebook_output_download(run.kernel_ref, output_dir=str(output_dir), force_download=True)
        except Exception as exc:
            return run.model_copy(
                update={
                    "status": "running",
                    "detail": (
                        "KaggleHub could not download notebook outputs yet. "
                        "If kernel_ref is a dataset handle, run a Kaggle notebook and sync with its notebook output handle. "
                        f"{str(exc)[-500:]}"
                    ),
                }
            )
        return run.model_copy(
            update={
                "status": "completed",
                "local_path": str(downloaded or output_dir),
                "detail": "KaggleHub notebook outputs downloaded and ready for encoder artifact activation.",
            }
        )

    def _training_payload(
        self,
        request: KaggleTrainingRequest,
        training_history: list[TrainingIngestResponse],
        world_model_candidates: list[WorldModelCandidate],
    ) -> dict[str, Any]:
        workspace_id = request.workspace_id
        filtered = [
            item
            for item in training_history
            if workspace_id is None or item.signature.workspace_id in {None, workspace_id}
        ]
        return {
            "task_type": request.task_type,
            "title": request.title,
            "notes": request.notes,
            "workspace_id": workspace_id,
            "created_at": utc_now().isoformat(),
            "sppe_pairs": [item.sppe_training_pair.model_dump(mode="json") for item in filtered],
            "signatures": [item.signature.model_dump(mode="json") for item in filtered],
            "world_model_candidates": [candidate.model_dump(mode="json") for candidate in world_model_candidates],
        }

    def _dataset_metadata(self, request: KaggleTrainingRequest) -> dict[str, Any]:
        return {
            "id": self._dataset_handle(request),
            "title": request.title[:80],
            "is_private": True,
            "licenses": [{"name": "CC0-1.0"}],
            "keywords": ["jims-ai", request.task_type, "memory-centric-ai"],
        }

    def _dataset_handle(self, request: KaggleTrainingRequest) -> str:
        return f"{self._dataset_owner()}/{self._slug(f'jimsai-{request.task_type}')}"

    def _dataset_owner(self) -> str:
        owner = os.getenv("KAGGLE_DATASET_OWNER", "").strip() or os.getenv("KAGGLE_USERNAME", "").strip()
        return owner

    def _kagglehub_available(self) -> bool:
        try:
            import kagglehub  # noqa: F401
        except Exception:
            return False
        return True

    def _slug(self, value: str) -> str:
        slug = "".join(char.lower() if char.isalnum() else "-" for char in value)
        slug = "-".join(part for part in slug.split("-") if part)
        return slug[:48] or "jimsai-training"
